interface JQueryElement {
    length: number;

    appendTo(pElement: JQueryElement): JQueryElement;
    insertAfter(pElement: JQueryElement): JQueryElement;
    insertBefore(pElement: JQueryElement): JQueryElement;
    remove(): JQueryElement;
    show(pTime: number, pFunction?: Function): JQueryElement;
    hide(pTime: number, pFunction?: Function): JQueryElement;
    fadeIn(pnumber: number, pFunction?: Function): JQueryElement;
    fadeOut(pTime: number, pFunction?: Function): JQueryElement;
    select(): JQueryElement;
    html(pStr: string): void;
    find(pSelector: string): JQueryElement;
    css(pStyles: Object): JQueryElement;
    first(): JQueryElement;
    addClass(pClassName: string): JQueryElement;
    removeClass(pClassName: string): JQueryElement;
    append(JQueryElement: JQueryElement): JQueryElement;
    text(): string;
    next(): JQueryElement;
    prev(): JQueryElement;
    keydown(pFunction: Function): JQueryElement;
    keyup(pFunction: Function): JQueryElement;
    keypress(pFunction: Function): JQueryElement;
    focusout(pFunction: Function): JQueryElement;
    focusin(pFunction: Function): JQueryElement;    
    blur(pFuction: Function): JQueryElement;
    addClass(pClassName: string): JQueryElement;
    removeClass(pClassName: string): JQueryElement;
    animate(pCssObject: Object, pTime: number): JQueryElement;
    offset(): Offset;
    scrollTop(pValue?: number): number;
    height(): number;
    outerHeight(): number;
    text(pStr: string): JQueryElement;
    val(pStr?: string): string;
    attr(pProp: string, pValue: Boolean | string): JQueryElement;
    data(pStr: string, pValue: string): JQueryElement;
    get(pIndex: number): JQueryElement;
    text(): string;
}